# Site settings
author: Katie T. Le
title: Katie's coding journey 
header-img: img/home-bg.png
email: lethikatie@gmail.com
copyright_name: Katie T. Le
description: > # this means to ignore newlines until "baseurl:"
  A documentation of me and coding.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  katiethile

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
